/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type { Escrow, EscrowInterface } from "../../Escrow_Dummy.sol/Escrow";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "budget",
        type: "uint256",
      },
    ],
    name: "UpdatedEvent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    name: "update_mapping_then_asset_failure",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "budget",
        type: "uint256",
      },
    ],
    name: "update_mapping_then_revert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "budget",
        type: "uint256",
      },
    ],
    name: "update_mappingthen_success",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610315806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806355215700146100465780637100e8db14610074578063ec576eb9146100ac575b600080fd5b6100726004803603602081101561005c57600080fd5b81019080803590602001909291905050506100e4565b005b6100aa6004803603604081101561008a57600080fd5b810190808035906020019092919080359060200190929190505050610195565b005b6100e2600480360360408110156100c257600080fd5b8101908080359060200190929190803590602001909291905050506101ef565b005b60008060008381526020019081526020016000205490507f9635d8c2bd4b448a97e7a1589ecc0456cded483d61c72c79ef3109d8ed9b1d5c8282604051808381526020018281526020019250505060405180910390a16000610191576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252602c8152602001806102b4602c913960400191505060405180910390fd5b5050565b80600080848152602001908152602001600020819055507f9635d8c2bd4b448a97e7a1589ecc0456cded483d61c72c79ef3109d8ed9b1d5c8282604051808381526020018281526020019250505060405180910390a15050565b80600080848152602001908152602001600020819055507f9635d8c2bd4b448a97e7a1589ecc0456cded483d61c72c79ef3109d8ed9b1d5c8282604051808381526020018281526020019250505060405180910390a16040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252601b8152602001807f526576657274696e6720666f722064656d6f6e7374726174696f6e000000000081525060200191505060405180910390fdfe416c77617973206661696c20746f2064656d6f6e73747261746520617373657274696f6e206661696c757265a26469706673582212208d0dbba238fb4cbe2f70bc00a7a4ebf2d3f2f2c718432888da18beca2165763464736f6c63430007030033";

type EscrowConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EscrowConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Escrow__factory extends ContractFactory {
  constructor(...args: EscrowConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Escrow> {
    return super.deploy(overrides || {}) as Promise<Escrow>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Escrow {
    return super.attach(address) as Escrow;
  }
  override connect(signer: Signer): Escrow__factory {
    return super.connect(signer) as Escrow__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EscrowInterface {
    return new utils.Interface(_abi) as EscrowInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Escrow {
    return new Contract(address, _abi, signerOrProvider) as Escrow;
  }
}
